#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp32_device

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/protocol_examples_common += /home/joaovitor/esp/esp-idf-lib-master/components


include $(IDF_PATH)/make/project.mk
